baseURL ="https://forzaeth.ch/"
title = "ForzaETH"
author = "forzaeth"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog', 'events']
  sponsors = ['sponsors']

  googleFonts = true

  [params.logo]
    main = "logos/logo.svg"
    alt = "ForzaETH Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "ForzaETH by Autonomous Racing Z端rich"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "ForzaETH is the F1TENTH Team of Autonomous Racing Z端rich"
    meta_og_title = "ForzaETH by Autonomous Racing Z端rich"
    meta_og_type = "website"
    meta_og_url = "https://forzaeth.ch"
    meta_og_description = "ForzaETH is the F1TENTH Team of Autonomous Racing Z端rich"


[menu]

  #[[menu.main]]
  #  identifier = "cars"
  #  name = "Cars"
  #  url = "/cars/"
  #  weight = 3

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 5
  
  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2

  [[menu.footer]]
    name = "Instagram"
    url = "https://instagram.com/forzaeth/"
    pre = "Instagram"
      weight = 3


  [[menu.footer]]
    name = "Linkedin"
    url = "https://www.linkedin.com/company/forzaeth-arzh/"
    pre = "Linkedin"
      weight = 3


  [[menu.footer]]
    name = "GitHub"
    url = "https://https://github.com/ForzaETH"
    pre = "GitHub"
      weight = 3